### ISSUE TITLE
Issue with Open Management Portal in Tab

### ISSUE THREAD

**Issue by hbadian** [intersystems-community/intersystems-servermanager#181]
I am adding a bunch of instances to VS Code. Most of them allow me to Open Management Portal in Tab. Some of them do not. I did change the /csp/sys Web Apps as directed and it does not work. Any help would be appreciated.

**Comment by gjsjohnmurray** [comment]
@hbadian can you spot any factor that differentiates the servers you **can** open Portal in Simple Browser (aka tab) for versus the servers where you can't? For example $zversion string? Or whether the Portal URL is http or https?

And when Simple Browser fails to open the Portal page are you at least getting prompted for credentials but then re-prompted when you click Login?

**Comment by hbadian** [comment]
They are all https. I did think I noticed a difference at first because 2 of the failing ones are: IRIS for UNIX (Red Hat Enterprise Linux 7 for x86-64) 2022.1.2 (Build 574U) Fri Jan 13 2023 14:57:52 EST [Health:3.5.0-1.m1]. 
All the successful ones are: HealthShare Unified Care Record 2022.2.2 Build: 1000 Adhoc: 22313 [HealthShare Modules: Health Insight:24.0 + Core:24.0 + Patient Index:24.0] - IRIS for UNIX (Red Hat Enterprise Linux 7 for x86-64) 2022.1 (Build 209_0_22313U) Fri Mar 17 2023 17:16:19 EDT [Health Insight:24.0|Core:24.0|Patient Index:24.0].

However 2 of the failures are also the same 2022.2.2 as above.

**Comment by hbadian** [comment]
Also, I do get prompted for credentials and then reprompted when clicking Login

**Comment by gjsjohnmurray** [comment]
Troubleshooting problems getting Portal to run in Simple Browser is notoriously tricky.

I assume you've double-checked that the "Use Cookie for Session" setting is "Autodetect" for all five /csp/sys* web apps?

Maybe also try altering the "Prevent login CSRF attack" checkbox setting. If changing it makes no difference, put it back to the old state.

Are any of the web servers using self-signed certs? I think that's unlikely, since in my experience this situation yields completely blank pages (no login prompts, and a message `[error] CodeWindow: failed to load (reason: ERR_CERT_AUTHORITY_INVALID, code: -202)` in the Main channel of the Output tab of Panel).

Do you get the same result if you run the Simple Browser command from VS Code Command Palette and enter a portal URL, e.g. https://webserver/pathPrefix/csp/sys/UtilHome.csp ?

**Comment by gjsjohnmurray** [comment]
Yes, makes sense. Glad to hear this fixed it for you.
