### ISSUE TITLE
Add ability to put default password for username in keystore

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/intersystems-servermanager#38]
Suggested by @lindensc in https://github.com/intersystems-community/vscode-objectscript/issues/255#issuecomment-704626928

**Comment by theflyingape** [comment]
Perhaps related and can help simplify: when selecting a **2nd** server to connect, the bottom status bar goes looping wildly _while_ Code prompts for my password, even though it's stored proper in the keychain for each server.  Since we use AD for central authentication, it locks out my account by policy, ugh.

References: [COS #424](https://github.com/intersystems-community/vscode-objectscript/issues/424), [COS #417](https://github.com/intersystems-community/vscode-objectscript/issues/417)

**Comment by gjsjohnmurray** [comment]
@theflyingape please see https://github.com/intersystems-community/vscode-objectscript/issues/616. A fix is about to merge, and I will ping you from there shortly to ask you to try the beta VSIX.

**Comment by theflyingape** [comment]
I can confirm the ObjectScript 1.0.10beta behaves much closer to expected with the updated Server Manager 2.0.2.
The backend logs sometimes show multiple attempts to fully login (non-cached hits); but subsequent operations & reloads perform a single-hit.

**Comment by gjsjohnmurray** [comment]
@theflyingape thanks for the feedback. I'll try and get 1.0.10 released soon.

**Comment by gjsjohnmurray** [comment]
Decided not to implement option for a global password.
